### ISSUE TITLE
segmentation fault on error: file is unreadable

### ISSUE THREAD

**Issue by Anton-4** [lukewilliamboswell/basic-ssg#6]
[Relevant source code](https://github.com/lukewilliamboswell/basic-ssg/blob/7bef6f918554c9692785686295b65b5a85b2c515/crates/ssg/src/lib.rs#L306)

This happens when you have a [typo in the file reference](https://github.com/roc-lang/examples/commit/d11c686f73620d8ff5fdb1ca379dc5da6e336974).

```
+ ./www/main www/content/ www/build/
...
www/build/examples/EncodeDecode/README.html successfully written to disk
./www/build.sh: line 105: 39566 Segmentation fault      (core dumped) ./www/main www/content/ www/build/
```
Only when running with valgrind can I see the actual error:
```
(ParseError "ERROR File "www/content/examples/ImportPackageFromModule/module.roc" is unreadable:
	No such file or directory (os error 2)")
```
The error is followed by memory garbage that I can't paste into github:
![Screenshot_20240903_140121](https://github.com/user-attachments/assets/7b01cdba-5025-4c56-b8bc-0c08e7fc3fd3)

It's likely that the `message` [here](https://github.com/lukewilliamboswell/basic-ssg/blob/7bef6f918554c9692785686295b65b5a85b2c515/crates/roc_host/src/lib.rs#L202) is not a proper `RocStr`.

Full valgrind_ouput:
[valgrind_output.log](https://github.com/user-attachments/files/16848237/valgrind_output.log)

**Comment by Anton-4** [comment]
- [ ] I recommend adding a test for this kind of typo error after this is fixed

**Comment by lukewilliamboswell** [comment]
So the case where there is a typo should give a proper handled error. But in this case I think the issue is that the return type for that effect in the host is not correct. It needs to be updated for builtin task to return a RocResult (even though it exits the program).
